const API = [
  {
    idLicitacao: 109269,
    dataInicioPropostas: "21/06/2020",
    horaInicioPropostas: "12:00",
    dataFinalPropostas: "21/06/2020",
    horaFinalPropostas: "12:00",
    dataLimiteImpugnacao: "21/06/2020",
    horaLimiteImpugnacao: "12:00",
    dataAberturaPropostas: "21/06/2020",
    horaAberturaPropostas: "12:01",
    dataPublicacao: "20/06/2020",
    horaPublicacao: "22:40",
    NR_PROCESSO: "20.06.20 Fila Fechado Lote Global",
    NUMERO: "20.06.20 Fila Fechado Lote Global",
    idSituacao: 6,
    NR_LICITACAO: null,
    ANO_LICITACAO: null,
    DS_OBJETO: "20.06.20 Fila Fechado Lote Global",
    prazoValidade: "",
    anulacao: null,
    legislacaoAplicavel: 1,
    aplicar147: false,
    exclusivoMPE: false,
    beneficioLocal: false,
    casasDecimais: 2,
    apresentaValorReferencia: false,
    exigeGarantia: false,
    exigeCarona: false,
    separarPorLotes: true,
    operacaoLote: "Disputa por Valor Global",
    mensagemAlerta:
      "Os vencedores do processo correspondem ao ranking formado no dia 16/11/2023 às 16:38.",
    origensRecursos: [
      {
        cdTipoOrigem: 1,
        tipoOrigem: "Próprio",
        numeroOrigem: "",
      },
    ],
    tratamentoFaseLance: "Aberto e Fechado",
    modalidade: {
      idModalidadeLicitacao: 1,
      modalidadeLicitacao: "Pregão",
      idTipoLicitacao: 1,
      tipoLicitacao: "Pregão Eletrônico",
      tipoRealizacao: "Eletrônico",
      tipoJulgamento: "Menor Preço",
    },
    situacao: "Encerrado para Operação",
    pregoeiro: {
      nome: "Pregoeiro Luiz",
      CPF: "79264549072",
    },
    autoridadeCompetente: {
      nome: "Ordenador Luiz",
      CPF: "46371262076",
    },
    equipeDeApoio: [
      {
        NM_PESSOA: "Usuário Apoio1",
        CPF: "727.865.071-20",
        NR_DOCUMENTO: "727.865.071-20",
        DS_EMAIL: "gemeosdf@gmail.com",
        LOGRADOURO: "",
        CEP: "",
        BAIRRO: "",
        Cidade: null,
        CD_MUNICIPIO_IBGE: null,
        UF: null,
      },
      {
        NM_PESSOA: "Usuário Apoio 2",
        CPF: "296.056.122-83",
        NR_DOCUMENTO: "296.056.122-83",
        DS_EMAIL: "gemeosdf@gmail.com",
        LOGRADOURO: "",
        CEP: "",
        BAIRRO: "",
        Cidade: null,
        CD_MUNICIPIO_IBGE: null,
        UF: null,
      },
    ],
    unidadeCompradora: {
      idComprador: 991,
      idUnidadeCompradora: 1367,
      nomeComprador: "Prefeitura de Teste - Luiz",
      nomeUnidadeCompradora: "Undade Teste",
      Cidade: "Brasília",
      CD_MUNICIPIO_IBGE: "5300108",
      UF: "DF",
    },
    lotes: [
      {
        idLote: 4995,
        NR_LOTE: 2,
        CD_BOLEANO_D_DIVISIVEL: false,
        justificativa: null,
        cotaReservada: false,
        itens: [
          {
            IdItem: 4996,
            _id: "",
            NR_LOTE: 2,
            DS_ITEM: "Item 3",
            QT_ITENS: 1,
            VL_UNITARIO_ESTIMADO: 1000,
            NR_ITEM: 1,
            CD_BOLEANO_D_EXCLUSIVO: false,
            justificativas: [],
            Propostas: [
              {
                IdItem: 4996,
                Data: "21/06/2020",
                Hora: "12:37:46",
                IdFornecedor: "11111111111111",
                Tipo: "Pessoa Jurídica",
                Modelo: "marca",
                Marca: "fab",
                Fabricante: "fab",
                Detalhamento: "teste",
                ValidadeProposta: "60",
                ValorUnitario: 171.29,
                ValorTotal: 171.29,
                Valido: true,
              },
            ],
            PropostasReadequadas: [
              {
                idLote: 4996,
                Data: "21/06/2020",
                Hora: "16:28:04",
                IdFornecedor: "11111114111111",
                Tipo: "Pessoa Jurídica",
                Valido: true,
                Justificativa: null,
                ValorUnitario: 21.75,
                ValorTotal: 21.75,
              },
            ],
            SG_UNIDADE_MEDIDA: "UN",
          },
          {
            IdItem: 4997,
            _id: "",
            NR_LOTE: 2,
            DS_ITEM: "Item 4",
            QT_ITENS: 1,
            NR_ITEM: 2,
            CD_BOLEANO_D_EXCLUSIVO: false,
            justificativas: [],
            Propostas: [
              {
                IdItem: 4997,
                Data: "21/06/2020",
                Hora: "12:37:39",
                IdFornecedor: "11111111111111",
                Tipo: "Pessoa Jurídica",
                Modelo: "marca",
                Marca: "fab",
                Fabricante: "fab",
                Detalhamento: "teste",
                ValidadeProposta: "60",
                ValorUnitario: 171.29,
                ValorTotal: 171.29,
                Valido: true,
              },
            ],
            PropostasReadequadas: [
              {
                idLote: 4997,
                Data: "21/06/2020",
                Hora: "16:28:04",
                IdFornecedor: "11111114111111",
                Tipo: "Pessoa Jurídica",
                Valido: true,
                Justificativa: null,
                ValorUnitario: 21.75,
                ValorTotal: 21.75,
              },
            ],
            SG_UNIDADE_MEDIDA: "UN",
          },
        ],
        DS_LOTE: "Lote 2",
        Lances: [
          {
            idLote: 4995,
            Data: "21/06/2020",
            Hora: "13:30:20",
            IdFornecedor: "11111113111111",
            Tipo: "Pessoa Jurídica",
            Valido: true,
            Justificativa: null,
            ValorUnitario: 1000,
            ValorTotal: 1000,
          },
        ],
        Inabilitados: [],
        Vencedores: [
          {
            Cancelado: false,
            idLote: 4995,
            RazaoSocial: "Empresa130",
            IdFornecedor: "11111114111111",
            Tipo: "Pessoa Jurídica",
            ValorUnitario: 43.5,
            ValorTotal: 43.5,
            Ranking: 1,
          },
        ],
        Reversoes: [],
        Reabilitacoes: [],
      },
      {
        idLote: 4998,
        NR_LOTE: 3,
        CD_BOLEANO_D_DIVISIVEL: false,
        justificativa: null,
        cotaReservada: true,
        itens: [
          {
            IdItem: 4999,
            _id: "",
            NR_LOTE: 3,
            DS_ITEM: "Item 5",
            QT_ITENS: 1,
            NR_ITEM: 1,
            CD_BOLEANO_D_EXCLUSIVO: false,
            justificativas: [],
            Propostas: [
              {
                IdItem: 4999,
                Data: "21/06/2020",
                Hora: "12:36:29",
                IdFornecedor: "11111111111111",
                Tipo: "Pessoa Jurídica",
                Modelo: "marca",
                Marca: "fab",
                Fabricante: "fab",
                Detalhamento: "teste",
                ValidadeProposta: "60",
                ValorUnitario: 500,
                ValorTotal: 500,
                Valido: true,
              },
            ],
            PropostasReadequadas: [
              {
                idLote: 4999,
                Data: "21/06/2020",
                Hora: "16:27:09",
                IdFornecedor: "11111111111111",
                Tipo: "Pessoa Jurídica",
                Valido: false,
                Justificativa: null,
                ValorUnitario: 500,
                ValorTotal: 500,
              },
            ],
            SG_UNIDADE_MEDIDA: "UN",
          },
          {
            IdItem: 5000,
            _id: "",
            NR_LOTE: 3,
            DS_ITEM: "Item 6",
            QT_ITENS: 1,
            NR_ITEM: 2,
            CD_BOLEANO_D_EXCLUSIVO: false,
            justificativas: [],
            Propostas: [
              {
                IdItem: 5000,
                Data: "21/06/2020",
                Hora: "12:36:38",
                IdFornecedor: "11111111111111",
                Tipo: "Pessoa Jurídica",
                Modelo: "marca",
                Marca: "fab",
                Fabricante: "fab",
                Detalhamento: "teste",
                ValidadeProposta: "60",
                ValorUnitario: 500,
                ValorTotal: 500,
                Valido: true,
              },
            ],
            PropostasReadequadas: [
              {
                idLote: 5000,
                Data: "21/06/2020",
                Hora: "16:27:09",
                IdFornecedor: "11111111111111",
                Tipo: "Pessoa Jurídica",
                Valido: false,
                Justificativa: null,
                ValorUnitario: 500,
                ValorTotal: 500,
              },
            ],
            SG_UNIDADE_MEDIDA: "UN",
          },
        ],
        DS_LOTE: "Lote 3",
        Lances: [
          {
            idLote: 4998,
            Data: "21/06/2020",
            Hora: "13:28:21",
            IdFornecedor: "11111113111111",
            Tipo: "Pessoa Jurídica",
            Valido: true,
            Justificativa: null,
            ValorUnitario: 1090,
            ValorTotal: 1090,
          },
        ],
        Inabilitados: [],
        Vencedores: [
          {
            Cancelado: false,
            idLote: 4998,
            RazaoSocial: "Empresa110",
            IdFornecedor: "11111112111111",
            Tipo: "Pessoa Jurídica",
            ValorUnitario: 1000.02,
            ValorTotal: 1000.02,
          },
        ],
        Reversoes: [],
        Reabilitacoes: [],
      },
      {
        idLote: 4992,
        NR_LOTE: 1,
        CD_BOLEANO_D_DIVISIVEL: false,
        cotaReservada: false,
        justificativa: null,
        itens: [
          {
            IdItem: 4993,
            _id: "",
            NR_LOTE: 1,
            DS_ITEM: "Item 1",
            QT_ITENS: 1,
            NR_ITEM: 1,
            CD_BOLEANO_D_EXCLUSIVO: false,
            justificativas: [],
            Propostas: [
              {
                IdItem: 4993,
                Data: "21/06/2020",
                Hora: "12:40:13",
                IdFornecedor: "11111111111111",
                Tipo: "Pessoa Jurídica",
                Modelo: "marca",
                Marca: "fab",
                Fabricante: "fab",
                Detalhamento: "teste",
                ValidadeProposta: "60",
                ValorUnitario: 171.29,
                ValorTotal: 171.29,
                Valido: true,
              },
            ],
            PropostasReadequadas: [
              {
                idLote: 4993,
                Data: "21/06/2020",
                Hora: "16:27:52",
                IdFornecedor: "11111114111111",
                Tipo: "Pessoa Jurídica",
                Valido: true,
                Justificativa: null,
                ValorUnitario: 21.75,
                ValorTotal: 21.75,
              },
            ],
            SG_UNIDADE_MEDIDA: "UN",
          },
          {
            IdItem: 4994,
            _id: "",
            NR_LOTE: 1,
            DS_ITEM: "Item 2",
            QT_ITENS: 1,
            NR_ITEM: 2,
            CD_BOLEANO_D_EXCLUSIVO: false,
            justificativas: [],
            Propostas: [
              {
                IdItem: 4994,
                Data: "21/06/2020",
                Hora: "12:40:05",
                IdFornecedor: "11111111111111",
                Tipo: "Pessoa Jurídica",
                Modelo: "marca",
                Marca: "fab",
                Fabricante: "fab",
                Detalhamento: "teste",
                ValidadeProposta: "60",
                ValorUnitario: 171.29,
                ValorTotal: 171.29,
                Valido: true,
              },
            ],
            PropostasReadequadas: [
              {
                idLote: 4994,
                Data: "21/06/2020",
                Hora: "16:27:52",
                IdFornecedor: "11111114111111",
                Tipo: "Pessoa Jurídica",
                Valido: true,
                Justificativa: null,
                ValorUnitario: 21.75,
                ValorTotal: 21.75,
              },
            ],
            SG_UNIDADE_MEDIDA: "UN",
          },
        ],
        DS_LOTE: "Lote 1",
        Lances: [
          {
            idLote: 4992,
            Data: "21/06/2020",
            Hora: "13:29:42",
            IdFornecedor: "11111113111111",
            Tipo: "Pessoa Jurídica",
            Valido: true,
            Justificativa: null,
            ValorUnitario: 1000,
            ValorTotal: 1000,
          },
        ],
        Inabilitados: [],
        Vencedores: [
          {
            Cancelado: false,
            idLote: 4992,
            RazaoSocial: "Empresa130",
            IdFornecedor: "11111114111111",
            Tipo: "Pessoa Jurídica",
            ValorUnitario: 43.5,
            ValorTotal: 43.5,
          },
        ],
        Reversoes: [],
        Reabilitacoes: [],
      },
    ],
    MensagensPregoeiro: [
      {
        Assunto:
          "Negociação aberta para o processo 20.06.20 Fila Fechado Lote Global",
        DataEnvio: "21/06/2020",
        HoraEnvio: "16:08",
        mensagem:
          "Você recebeu um novo pedido de negociação nos lotes 1,2 do processo 20.06.20 Fila Fechado Lote Global.<br><br>Acesse o seu ambiente logado para verificar os detalhes.",
      },
    ],
    MensagensChat: [
      {
        Apelido: "Sistema",
        Data: "21/06/2020",
        Hora: "13:57:15",
        Frase: "O processo está em fase de análise das propostas",
      },
    ],
    Impugnacoes: [
      {
        DataImpugnacao: "16/10/2023",
        HoraImpugnacao: "12:21:44",
        Pedido: "teste",
        TextoImpugnacao: "texto",
        DataResposta: "16/10/2023",
        HoraResposta: "12:23:45",
        ResultadoJulgamento: "Deferido Parcialmente",
        Julgamento: "xxxxxxx",
        historicoRecursos: [
          {
            idHistorico: 1111111,
            dataResposta: "2023/10/16",
            horaResposta: "12:23:21",
            julgamento: "xxxxxxxxxx",
            resultadoJulgamento: "Deferido Parcialmente",
            nomeAnexo: "xxxxxxxxxx",
            idArquivoAnexo: "1111111111",
          },
          {
            idHistorico: 1111111,
            dataResposta: "2023/10/16",
            horaResposta: "12:23:45",
            julgamento: "texto",
            resultadoJulgamento: "Deferido Parcialmente",
            nomeAnexo: "xxxxxxx",
            idArquivoAnexo: "111111111",
          },
        ],
        Impugnante: {
          RazaoSocial: "Empresa",
          Tipo: "Pessoa Jurídica",
          CPF: "11111111111",
          CNPJ: "111111111111111",
          Registro: "111111111",
          INSCRICAO_ESTADUAL: "1111111",
          INSCRICAO_MUNICIPAL: "1111111111",
          Email: "teste@gmail.com",
          NomeFantasia: "Empresa2",
          Endereco: "xxxxxxxxxxxx",
          Numero: "1111111111",
          Complemento: "1111111111111",
          Bairro: "xxxxxx",
          Telefone: "11+111111111_",
          CEP: "11111111",
        },
      },
    ],
    Suspensoes: [],
    Cancelamentos: [],
    Publicacao: [
      {
        CD_ARQUIVO: ["1179"],
        TIPO_EVENTO: "Publicação do Edital",
        SIGLA_LICITACON: "PUE",
        DATA: "20/06/2020",
        HORA: "22:40:17",
        EVENTO: "O edital do processo foi publicado.",
        DETALHE_EVENTO: null,
        CD_TIPO_FASE: "EPU",
      },
    ],
    Republicacao: [],
    Reinicio: [],
    Revogacao: [],
    Encerramento: [],
    Notificacoes: [
      {
        CD_ARQUIVO: ["1179"],
        TIPO_EVENTO: "Publicação do Edital",
        SIGLA_LICITACON: "PUE",
        DATA: "20/06/2020",
        HORA: "22:40:17",
        EVENTO: "O edital do processo foi publicado.",
        DETALHE_EVENTO: null,
        CD_TIPO_FASE: "EPU",
      },
      {
        CD_ARQUIVO: [],
        TIPO_EVENTO: "Mudança de fase",
        SIGLA_LICITACON: "HAP",
        DATA: "21/06/2020",
        HORA: "13:57:15",
        EVENTO: "Processo mudou para fase de Habilitação/Propostas",
        DETALHE_EVENTO: null,
        CD_TIPO_FASE: "EPU",
      },
    ],
    CD_TIPO_FASE_ATUAL: "ADH",
    Participantes: [
      {
        RazaoSocial: "Empresa100",
        Tipo: "Pessoa Jurídica",
        CNPJ: "11111111111111",
        CPF: "11111111111",
        Registro: null,
        NomeFantasia: "Empresa100",
        Endereco: "em",
        Numero: "234",
        Complemento: "3241",
        Bairro: "Sia",
        Telefone: "61+21600000_",
        CEP: "71000000",
        INSCRICAO_ESTADUAL: null,
        INSCRICAO_MUNICIPAL: null,
        DeclaracaoME: false,
        Licitante: true,
        TipoEmpresa: "Ltda/Eireli",
        RepresentanteLegal: {
          Nome: "empresa100",
          CPF: "11111111111",
          Telefone: "",
          Endereco: "",
          Cidade: "",
          Bairro: "",
          CEP: "",
          CD_MUNICIPIO_IBGE: null,
          UF: null,
        },
        Cidade: "Brasília",
        CD_MUNICIPIO_IBGE: "5300108",
        UF: "DF",
        Email: "luiz.paulo@wcompras.com.br",
      },
    ],
    Duvidas: [],
  },
];

const extrairPropostas = (processos) => {
  const resultados = [];

  processos.forEach((processo) => { 
    (processo.lotes || []).forEach((lote) => {
      (lote.itens || []).forEach((item) => {
        const propostas = Array.isArray(item.Propostas) ? item.Propostas : [];
        const propostasReadequadas = Array.isArray(item.PropostasReadequadas)
          ? item.PropostasReadequadas
          : [];

        propostas.forEach((proposta) => {
          const negociacao =
            propostasReadequadas.find(
              (readequada) =>
                readequada.IdFornecedor === proposta.IdFornecedor ||
                readequada.idLote === item.IdItem
            ) || propostasReadequadas[0] || null;

          resultados.push({
            processo: processo.NUMERO || processo.NR_PROCESSO || null,
            lote: lote.NR_LOTE || null,
            item: item.DS_ITEM || null,
            valorProposta: proposta.ValorTotal ?? proposta.ValorUnitario ?? null,
            valorUnitario: proposta.ValorUnitario ?? null,
            valorNegociado: negociacao
              ? negociacao.ValorTotal ?? negociacao.ValorUnitario ?? null
              : null,
            marcaFabricante: proposta.Marca || proposta.Fabricante || null,
            modeloVersao: proposta.Modelo || proposta.Detalhamento || null,
          });
        });
      });
    });
  });

  return resultados;
};

console.log(JSON.stringify(extrairPropostas(API), null, 2));